###
# 9 spans
POST http://gate.test/v2/payment/card/payout HTTP/1.1
user-agent: vscode-restclient
cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json
x-b3-traceid: 109
x-b3-spanid: 222
x-b3-parentspanid: 333
x-b3-sampled: 1

{
  "general": {
    "project_id": 3,
    "payment_id": "ORDER_ID_C00540_0710_006",
    "signature": "9u4mQ15z8hUzg7Z1a69ooshSphgJQ4bSmvHP1OhV\/1tTOddXafaJ902Ry2XnRDHpSY0Lw7gCp4Cls7YDr388\/w=="
  },
  "card": {
    "pan": "4000000000000002",
    "year": 2020,
    "month": 1
  },
  "user": {
    "id": "USER ID",
    "country": "RU",
    "ip_address": "1.2.3.4"
  },
  "order": {
    "amount": 780,
    "currency": "RUB",
    "description": "CreditPilot"
  }
}

### 19 штук
# home: 
POST http://gate.test/v2/payment/card/payout HTTP/1.1
Cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json

{
  "general": {
    "project_id": 16,
    "payment_id": "lol_528",
    "signature": "9u4mQ15z8hUzg7Z1a69ooshSphgJQ4bSmvHP1OhV\/1tTOddXafaJ902Ry2XnRDHpSY0Lw7gCp4Cls7YDr388\/w=="
  },
  "card": {
    "pan": "4000000000000002",
    "year": 2020,
    "month": 1
  },
  "user": {
    "id": "USER ID",
    "country": "RU",
    "ip_address": "1.2.3.4"
  },
  "order": {
    "amount": 780,
    "currency": "RUB",
    "description": "CreditPilot"
  }
}

###
POST http://plus.test/gate/ HTTP/1.1
Cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json

{
  "name": "CardViaPayBox",
  "type": "purchase",
  "operation_id": 1,
  "merchant_params": {
    "merchant_id": 9975,
    "merchant_password": "vygasudecywykiry",
    "gateway_url": "http://mock.test/paybox/z/sagan/g2g/payment",
    "paymentacs_url": "http://mock.test/paybox/z/sagan/api/paymentAcs",
    "status_url": "http://mock.test/paybox/z/sagan/api/status"
  },
  "gate_id": "eco_dev",
  "amount": 5900,
  "currency": "KZT",
  "client_params": {
    "order_id": "2",
    "account": "4405645000006150",
    "cardholder": "John",
    "security_code": "653",
    "expiration": "2025-09-01T00:00:00+00:00"
  }
}


###
POST http://gate.test/v2/payment/card/sale HTTP/1.1
Cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json
# x-b3-traceid: 109
# x-b3-spanid: 222
# x-b3-parentspanid: 333
# x-b3-sampled: 3

{
  "general": {
    "project_id": 31,
    "payment_id": "ORDER_ID_C00400_1504594439",
    "signature": "6YA1m06cnT2YsM3VfvkGsjwM6bQff/njD0KL7uk/1ZxZm8EpdVoNRcxkZkE/K3Xb5NskLEDakrqjLcs8y0OWoQ=="
  },
  "card": {
    "pan": "4200778272290595",
    "year": 2021,
    "month": 12,
    "card_holder": "HOLLY WARREN",
    "cvv": "101",
    "save": true
  },
  "user": {
    "id": "Kvadratych",
    "country": "RU",
    "ip_address": "1.2.3.4"
  },
  "order": {
    "amount": 1010,
    "currency": "RUB",
    "description": "alalala"
  }
}

###
GET http://gate.test/
Cookie: XDEBUG_SESSION=PHPSTORM
#x-b3-sampled: 3

###
# atava
# pmx: core-1035
# plus: plus-146
# ecotests: ./vendor/bin/codecept run cases PurchaseCest:C00400 -c ./tests/gate/payture/ —env local -d
POST http://gate.test/v2/payment/card/sale
content-type: application/json

{
  "general": {
    "project_id": 203,
    "payment_id": "5556544565",
    "signature": "No signature"
  },
  "card": {
    "pan": "4111111111100031",
    "year": 2020,
    "month": 1,
    "card_holder": "TONY RICHARDSON",
    "cvv": "123"
  },
  "customer": {
    "ip_address": "1.2.3.4",
    "id": "Petrovich",
    "phone": "79876543211"
  },
  "payment": {
    "amount": 777877,
    "currency": "RUB",
    "description": "Some description"
  }
}

###
# roundbank C00400
# 66 spans

POST http://gate.test/v2/payment/card/sale HTTP/1.1
cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json

{
  "general": {
    "project_id": 31,
    "payment_id": "ORDER_ID_C00400_0.40257800 1507630102",
    "signature": "Tl0ipFFa876nRmO/U/BInrTRSGY4E/787n456XWqD4zrpyNPc+O2V6lSDGprkveoOTi9CE25XW+onbSg+JOBRw=="
  },
  "card": {
    "pan": "4200778272290595",
    "year": 2021,
    "month": 12,
    "card_holder": "HOLLY WARREN",
    "cvv": "101",
    "save": true
  },
  "customer": {
    "id": "Kvadratych",
    "country": "RU",
    "ip_address": "1.2.3.4"
  },
  "payment": {
    "amount": 1010,
    "currency": "RUB",
    "description": "Описание заказа: акции по скидке визы"
  }
}