POST http://gate.dev/v2/payment/card/payout HTTP/1.1
user-agent: vscode-restclient
cookie: XDEBUG_SESSION=PHPSTORM
content-type: application/json
x-b3-traceid: 1
x-b3-spanid: 2
x-b3-parentspanid: 3
x-b3-sampled: 4

{
  "general": {
    "project_id": 3,
    "payment_id": "ORDER_ID_C00540_0710_106",
    "signature": "9u4mQ15z8hUzg7Z1a69ooshSphgJQ4bSmvHP1OhV\/1tTOddXafaJ902Ry2XnRDHpSY0Lw7gCp4Cls7YDr388\/w=="
  },
  "card": {
    "pan": "4000000000000002",
    "year": 2020,
    "month": 1
  },
  "user": {
    "id": "USER ID",
    "country": "RU",
    "ip_address": "1.2.3.4"
  },
  "order": {
    "amount": 780,
    "currency": "RUB",
    "description": "CreditPilot"
  }
}

###
GET http://gate.dev/
Cookie: XDEBUG_SESSION=PHPSTORM


